$lang{LIVING_SPACE}='Жила проща';
$lang{UTILITY_ROOM}='Нежила площа';
$lang{COMMERCIAL}='Комерційні приміщення';
$lang{OSBB}='ОСББ';
$lang{RENT}='Квартплата';
$lang{FILL_DEFAULT_VALUES_THAT_WILL_REPLACE_EMPTY_FILE_FIELDS} = 'Заповніть значення однакові для всіх жильців';
$lang{FILL_DEFAULT_VALUES_AND_CHOOSE_FILE_FOR_IMPORT} = 'Заповніть значення однакові для всіх жильців та виберіть файл для імпорту';
$lang{TOTAL_SPACE}='Загальна площа';
$lang{SPACE_TYPES}='Види приміщень';
$lang{SPENDING}='Розхід';
1;