$lang{OWNERSHIP_TYPE} = 'Тип собственности';
$lang{TOTAL_AREA}     = 'Общая площадь';
$lang{LIVING_AREA}    = 'Жилая площадь';
$lang{UTILITY_AREA}   = 'Дополнительная площадь';
$lang{BALCONY_AREA}   = 'Площадь балкона';
$lang{USEFUL_AREA}    = 'Полезная площадь';
$lang{ROOMS_COUNT}    = 'Количество комнат';
$lang{PEOPLE_COUNT}   = 'Количество жильцов';

$lang{COMMERCIAL}='Коммерческое помещение';
$lang{OSBB}='ОСББ';
$lang{RENT}='Квартплата';
$lang{FILL_DEFAULT_VALUES_THAT_WILL_REPLACE_EMPTY_FILE_FIELDS} = 'Заполните значения общие для всех жильцов';
$lang{FILL_DEFAULT_VALUES_AND_CHOOSE_FILE_FOR_IMPORT} = 'Заполните значения общие для всех жильцов и выб та виберите файл для импорта';
$lang{TOTAL_SPACE}      ='Общая площадь';
$lang{SPENDING}='Расход';
$lang{SPENDING_TYPES}='Типы расходов';
$lang{SPACE_TYPES}      ='Виды помещений';

$lang{TARIFS}           = 'Тарифы';
$lang{TARIF}            = 'Тариф';
$lang{UNIT}             = 'Тип начислений';
$lang{PRICE}            = 'Цена';
$lang{DOCUMENT_BASE}    = 'Документ-основание';
$lang{PAYMENT_NAME}     = 'Наименование услуги';
$lang{ADD_TARIF}        = 'Добавить тариф';
$lang{SET_TARIF_TO_ALL} = 'Установить тариф всем';
$lang{COME_INTO_FORCE}  = 'Вступает в силу с';
$lang{HOUSING}          = 'Жильцы';
$lang{MONTHLY_FEES}     = "Ежемесячные начисления";
$lang{FEES}             = "Начисления";

$lang{ACCOUNTING_BALANCE} = "Оборотно-сальдовая ведомость";
$lang{START_SALDO}      = "Сальдо на начало";
$lang{END_SALDO}        = "Сальдо на конец";
$lang{UNDER_CONSTRUCTION} = "В разработке";
$lang{FEES_ALREADY_EXISTS} = "За этот период уже начислено";
$lang{THANK_YOU}           ='Спасибо!';
$lang{ACCOUNT_INFORMATION} = 'Ваша учетная запись';
$lang{SITE} = 'Страница авторизации';
1;
